# Generated by Django 4.0 on 2021-12-30 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clothing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('collection', models.CharField(max_length=50)),
                ('size', models.CharField(choices=[('XS', 'very small'), ('S', 'small'), ('M', 'medium'), ('L', 'large'), ('XL', 'extra large'), ('XXL', 'extra extra large')], max_length=3)),
                ('type', models.CharField(choices=[('Jackets', 'jackets'), ('T-Shirts', 't-shirts'), ('Shirts', 'shirts'), ('Pants', 'pants'), ('Jeans', 'jeans'), ('Pullovers', 'pullovers'), ('Hoodies', 'hoodies'), ('Shoes', 'shoes'), ('Basics', 'basics'), ('Accessoires', 'accessoires'), ('Underwear', 'underwear'), ('Dresses', 'dresses'), ('Suits', 'suits')], max_length=12)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', related_query_name='user', to='auth.user')),
            ],
            options={
                'verbose_name': 'Clothing',
                'verbose_name_plural': 'Clothes',
                'ordering': ['name', '-type'],
            },
        ),
    ]
