# Generated by Django 4.0 on 2021-12-30 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('useradmin', '0002_rename_myuser_myuser_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clothing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('collection', models.CharField(max_length=50)),
                ('size', models.CharField(choices=[('XS', 'xs'), ('S', 's'), ('M', 'm'), ('L', 'l'), ('XL', 'xl'), ('XXL', 'xxl')], max_length=3)),
                ('type', models.CharField(choices=[('Jackets', 'jackets'), ('T-Shirts', 't-shirts'), ('Shirts', 'shirts'), ('Pants', 'pants'), ('Jeans', 'jeans'), ('Pullovers', 'pullovers'), ('Hoodies', 'hoodies'), ('Shoes', 'shoes'), ('Basics', 'basics'), ('Accessoires', 'accessoires'), ('Underwear', 'underwear'), ('Dresses', 'dresses'), ('Suits', 'suits')], max_length=12)),
                ('myuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clothing_created_by', related_query_name='clothing_created_by', to='useradmin.myuser')),
            ],
            options={
                'verbose_name': 'Clothing',
                'verbose_name_plural': 'Clothes',
                'ordering': ['name', '-type'],
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('up_or_down', models.CharField(choices=[('U', 'up'), ('D', 'down')], max_length=1)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('clothing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelclothing.clothing')),
                ('myuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useradmin.myuser')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('clothing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelclothing.clothing')),
                ('myuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useradmin.myuser')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'ordering': ['timestamp'],
            },
        ),
    ]
