# Generated by Django 4.0 on 2022-01-01 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('useradmin', '0001_initial'),
        ('modelclothing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='myuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useradmin.myuser'),
        ),
        migrations.AddField(
            model_name='comment',
            name='clothing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelclothing.clothing'),
        ),
        migrations.AddField(
            model_name='comment',
            name='myuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useradmin.myuser'),
        ),
        migrations.AddField(
            model_name='clothing',
            name='myuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clothing_created_by', related_query_name='clothing_created_by', to='useradmin.myuser'),
        ),
    ]
