# Generated by Django 4.0 on 2022-01-02 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelclothing', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothing',
            name='price',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=10),
        ),
    ]
