# Generated by Django 4.0 on 2022-01-02 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelclothing', '0003_clothing_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reported',
            field=models.BooleanField(default=False),
        ),
    ]
