# Generated by Django 4.0 on 2022-01-02 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelclothing', '0004_comment_reported'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothing',
            name='sex',
            field=models.CharField(choices=[('Male', 'male'), ('Female', 'female'), ('Unisex', 'unisex')], default='unisex', max_length=6),
        ),
    ]
