# Generated by Django 4.0 on 2022-01-03 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelclothing', '0005_clothing_sex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='up_or_down',
        ),
        migrations.AddField(
            model_name='vote',
            name='rating',
            field=models.IntegerField(default=5),
        ),
    ]
