# Generated by Django 4.0 on 2022-01-09 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelclothing', '0006_remove_vote_up_or_down_vote_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothing',
            name='pdffile',
            field=models.FileField(default='pdf_files/pdf-default.pdf', upload_to='pdf_files'),
        ),
        migrations.AddField(
            model_name='clothing',
            name='product_picture',
            field=models.ImageField(default='product_pictures/profile-default.jpg', upload_to='product_pictures/'),
        ),
    ]
