# Generated by Django 4.0 on 2022-01-09 18:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelclothing', '0007_clothing_pdffile_clothing_product_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothing',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
