# Generated by Django 4.0 on 2022-01-09 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelclothing', '0008_clothing_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='rating',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
