# Generated by Django 4.0 on 2022-01-09 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelclothing', '0009_comment_rating_alter_comment_text_delete_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothing',
            name='product_picture',
            field=models.ImageField(default='product_pictures/product-default.jpg', upload_to='product_pictures/'),
        ),
    ]
