# Generated by Django 4.0 on 2022-01-11 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelclothing', '0011_alter_comment_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.IntegerField(default='5'),
        ),
    ]
