# Generated by Django 4.0 on 2022-01-12 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelclothing', '0012_alter_comment_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothing',
            name='product_picture',
            field=models.ImageField(blank=True, upload_to='product_pictures/'),
        ),
    ]
