# Generated by Django 4.0 on 2022-01-14 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelclothing', '0014_remove_clothing_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='usefulness',
            field=models.IntegerField(default='0'),
        ),
    ]
