# Generated by Django 4.0 on 2022-01-14 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cartitem_product_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='product_collection',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product_color',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
