# Generated by Django 4.0 on 2022-01-01 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useradmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='type',
            field=models.CharField(choices=[('SU', 'superuser'), ('CS', 'customer service'), ('CU', 'customer'), ('BP', 'business partner')], default='CU', max_length=2),
        ),
    ]
