# Generated by Django 4.0 on 2021-12-30 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useradmin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='myuser',
            new_name='user',
        ),
    ]
