# Generated by Django 4.0 on 2022-01-02 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useradmin', '0003_alter_myuser_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='profile_picture',
            field=models.ImageField(default='img/profile-default.svg', upload_to='profile_pictures/'),
        ),
    ]
