# Generated by Django 4.0 on 2022-01-14 16:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useradmin', '0011_alter_myuser_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='date_of_birth',
            field=models.DateField(default=datetime.date(2002, 1, 14)),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='profile_picture',
            field=models.FileField(default='profile_pictures/profile-default.svg', upload_to='profile_pictures/'),
        ),
    ]
